export enum Environment {
  ENVIRONMENT = 'ENVIRONMENT',
  PORT = 'PORT',

  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_USERNAME = 'POSTGRES_USERNAME',
  POSTGRES_DATABASE = 'POSTGRES_DATABASE',
}
